"""
Embassy export helpers for the Synthetic Agora ("World B").

Closes the loop of the Inter-World Epistemic Embassy: previously, agents were only
narratively told to "deposit a ratified treaty" in `embassy/outbox/`, but nothing
ever enforced that this file was actually written — which is why this repo's own
outbox historically contained only the blank TREATY_TEMPLATE.md while the Frontier's
inbox already held hand-authored treaties. `export_treaty_to_embassy` removes that
reliance on the LLM "remembering" the exact template by deterministically rendering
a treaty document straight from a CANON_VERIFIED graph node's own data.
"""
import os
import re
from datetime import datetime, timezone
from typing import Dict, Any

from agora_graph import EpistemicGraph, get_shared_agora_dir


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _slugify(text: str, max_len: int = 48) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:max_len].rstrip("-") or "untitled"


def _get_embassy_outbox_dir() -> str:
    d = os.path.join(get_shared_agora_dir(), "embassy", "outbox")
    os.makedirs(d, exist_ok=True)
    return d


def _get_endorsing_families(node: Dict[str, Any]) -> set:
    """Mirrors EpistemicGraph._evaluate_quorum's family-counting rule exactly, so the
    export gate below can never diverge from what actually granted CANON_VERIFIED."""
    endorsements = [v for v in node.get("verifications", []) if v.get("verdict") == "endorse"]
    endorsing_families = {v.get("verifier_family") for v in endorsements if v.get("verifier_family")}
    if node.get("confidence", 0) >= 0.8 and node.get("author_family"):
        endorsing_families.add(node.get("author_family"))
    return endorsing_families


def _render_treaty(node: Dict[str, Any], originating_dossier_filename: str) -> str:
    endorsements = [v for v in node.get("verifications", []) if v.get("verdict") == "endorse"]
    endorser_families = sorted({v.get("verifier_family") for v in endorsements if v.get("verifier_family")})
    quorum_families = sorted(f for f in _get_endorsing_families(node) if f)
    verifiers = sorted({v.get("verifier_instance") for v in endorsements if v.get("verifier_instance")})
    author_family = node.get("author_family")
    author_credited = author_family in quorum_families and author_family not in endorser_families

    origin_line = (
        f"World A `{originating_dossier_filename}`"
        if originating_dossier_filename
        else "Originated within the Synthetic Agora (no incoming Frontier dossier)"
    )

    author_credit_note = (
        f" (the author's own lineage, `{author_family}`, is credited toward this quorum "
        "per the anti-echo rule at confidence \u2265 0.8, per EpistemicGraph._evaluate_quorum)"
        if author_credited else ""
    )

    artifact_lines = []
    if node.get("artifact_path"):
        artifact_lines.append(f"* `{node['artifact_path']}`")
    for v in endorsements:
        if v.get("reproduced_artifact_path"):
            artifact_lines.append(f"* `{v['reproduced_artifact_path']}` (replication by `{v['verifier_instance']}`)")
    if not artifact_lines:
        artifact_lines.append("* _No supplementary artifacts recorded._")

    return f"""# 🏛️ ⮀ 🌿 Ratified Epistemic Treaty
## Title: {node['title']}
**Originating Frontier Dossier:** {origin_line}
**Ratified Canon Node in World B:** `{node['id']}` (by `{node['author_instance']}`, verified by {', '.join(f'`{v}`' for v in verifiers) or 'N/A'})
**Epistemic Status:** **CANON VERIFIED** — anti-echo quorum satisfied across {len(quorum_families)} lineages: {', '.join(quorum_families) or 'N/A'}{author_credit_note}
**Date of Ratification:** {datetime.now(timezone.utc).strftime('%B %Y')}

---

### 📜 Formal Canonical Statement & Proof:

1. **Verified Invariant:** {node['summary']}
2. **Cross-Model Consensus:** Endorsed by {len(endorsements)} independent verification(s) from {', '.join(endorser_families) or 'N/A'} lineage(s){author_credit_note}.
3. **Prescription for Frontier Systems:** World A models may apply this ratified law when constructing related dynamical systems, cellular scaffolds, or multi-agent networks.

### 📦 Supporting Verification Artifacts in Agora:
{chr(10).join(artifact_lines)}

---
*Signed and sealed by the Epistemic Commonwealth of the Synthetic Agora.*
*Auto-generated by `export_treaty_to_embassy` from canon node `{node['id']}` on {utc_now_iso()}.*
"""


def export_treaty_to_embassy(node_id: str, originating_dossier_filename: str = "") -> str:
    """Deterministically renders and deposits a Ratified Epistemic Treaty for a CANON_VERIFIED node."""
    graph = EpistemicGraph()
    node_id = node_id.strip().upper()
    node = graph.nodes.get(node_id)

    if not node:
        return f"Error: Node '{node_id}' does not exist in the Epistemic DAG."

    if node.get("status") != "CANON_VERIFIED":
        return (
            f"Error: Node '{node_id}' has status '{node.get('status')}', not CANON_VERIFIED. "
            "A treaty can only be exported once the anti-echo quorum has ratified the node."
        )

    # Defense-in-depth check, but must mirror EpistemicGraph._evaluate_quorum's own
    # family-counting rule exactly (including the author-family credit at confidence >= 0.8) --
    # otherwise a node the graph itself already ratified as CANON_VERIFIED could be
    # incorrectly refused here.
    endorsing_families = _get_endorsing_families(node)
    if len(endorsing_families) < 2:
        return (
            f"Error: Node '{node_id}' does not yet have endorsements from at least two distinct "
            "model families. Refusing to export an unqualified treaty."
        )

    if node.get("exported_to_embassy"):
        treaty_file = node.get("treaty_file")
        treaty_path = os.path.join(_get_embassy_outbox_dir(), treaty_file) if treaty_file else None
        if treaty_path and os.path.isfile(treaty_path):
            return (
                f"Notice: Node '{node_id}' was already exported to the Embassy as "
                f"'{treaty_file}' on {node.get('exported_at')}. Skipping duplicate export."
            )
        # The flag says exported, but the file is missing (accidental deletion, cleanup,
        # etc.) -- self-heal by re-exporting instead of permanently trusting a stale flag.
        print(f"[Embassy] WARNING: Node '{node_id}' was marked exported but its treaty file "
              f"('{treaty_file}') is missing from embassy/outbox/. Re-exporting to repair.")

    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    filename = f"TREATY-agora-{date_str}-{node_id.lower()}-{_slugify(node['title'])}.md"
    outbox_dir = _get_embassy_outbox_dir()
    dest_path = os.path.join(outbox_dir, filename)

    content = _render_treaty(node, originating_dossier_filename)
    with open(dest_path, "w", encoding="utf-8") as f:
        f.write(content)

    node["exported_to_embassy"] = True
    node["treaty_file"] = filename
    node["exported_at"] = utc_now_iso()
    graph.save()

    return (
        f"Successfully exported Ratified Treaty for node '{node_id}' to "
        f"'embassy/outbox/{filename}'. It will be picked up by the Frontier on its next sync."
    )
